apiVersion: apps/v1

kind: Deployments
metadata:
  name: myapp-deployments
  labels:
    app: myapp
    type: front-end
spec: # RS
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec: # POD
      containers: # Array or List
        - name: nginx-app
          image: nginx
  replicas: 2
  selector: # Difference between RC and RS
    matchLabels: # matches with label on the POD
        type: front-end

