apiVersion: v1
kind: Service
metadata:
  name: service-map
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector: #labels from POD definition file
    app: myapp
    type: front-end
    
    
================================

apiVersion: v1
kind: Service
metadata:
  name: service-map
spec:
  type: ClusterIP # Default type
  ports:
    - targetPort: 80
      port: 80
  selector: #labels from POD definition file
    app: myapp
    type: front-end
